# Generated by Django 3.0.7 on 2020-06-22 04:26

import account_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0003_auto_20200621_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=account_settings.models.upload_location)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ProfilePhoto',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
