# Generated by Django 3.0.7 on 2020-06-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_settings', '0004_auto_20200622_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
