# Generated by Django 3.0.7 on 2020-06-22 11:44

import account_settings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_settings', '0005_profilephoto_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilephoto',
            options={},
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.ImageField(blank=True, default='app/user.svg', upload_to=account_settings.models.upload_location),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
