# Generated by Django 3.0.7 on 2020-06-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0007_auto_20200622_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
